dist: trusty
sudo: required

language: go

go:
  - 1.8

before_install:
  - sudo apt-get install --yes -qq docker docker-engine

install:
  - go get -t ./...

script:
  - go test -v ./...

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t optician-api .;
    docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD";
    docker tag optician-api theopticians/optician-api;
    docker push theopticians/optician-api;
    fi
